# Server Config
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3306/api_db"
    username: "root"
    password: "soft-cr-ninja-dev"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui.html
#logging:
#  level:
#    root: debug
